cask_args appdir: '/Applications'

tap 'homebrew/services'
tap 'jhawthorn/fzy'
## CLI

brew 'git'
brew 'libgit2'
brew 'hub'
brew 'vim'
brew 'ctags'
brew 'tmux'
brew 'htop'
brew 'reattach-to-user-namespace'
brew 'go'
brew 'fortune'
brew 'sl' # Corrects bad typing
brew 'tree'
brew 'yadm'
brew 'mas'
brew 'git-crypt'
brew 'zplug'
brew 'fzy'
brew 'fzf'
brew 'yarn'
brew 'nmap'
brew 'diff-so-fancy'
brew 'node'
brew 'nvm'

## Work
## brew 'crowdin'
## brew 'emp'
##cask 'osxfuse'
## brew 'datawire/blackbird/telepresence'

## Applications

cask 'google-chrome'
cask 'firefox'
cask 'cloudapp'
cask 'slack'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'spotify'
cask 'spotify-notifications'
cask 'teamviewer'
cask 'docker'
cask 'visual-studio-code'
cask 'postman'
cask 'mongodb-compass'
cask 'whatsapp'
cask 'notion'
cask 'mysqlworkbench'

## Fonts

cask 'font-menlo-for-powerline'
cask 'font-monoid-nerd-font'
