cask_args appdir: '/Applications'

tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'jhawthorn/fzy'
tap 'neovim/neovim'
tap 'socratessystems/socrates'

## CLI

brew 'git'
brew 'libgit2'
brew 'the_silver_searcher'
brew 'postgresql'
brew 'mysql'
brew 'redis'
brew 'hub'
brew 'vim'
brew 'neovim'
brew 'ctags'
brew 'tmux'
brew 'htop'
brew 'reattach-to-user-namespace'
brew 'go'
brew 'fortune'
brew 'sl' # Corrects bad typing
brew 'tree'
brew 'yadm'
brew 'mas'
brew 'git-crypt'
brew 'zplug'
brew 'fzy'
brew 'fzf'
brew 'yarn'
brew 'nmap'
brew 'diff-so-fancy'

## Elixir

brew 'elixir'

## Applications

cask 'google-chrome'
cask 'firefox'
cask 'cloudapp'
cask 'slack'
cask 'iterm2'
cask 'spectacle'
cask 'alfred'
cask 'jetbrains-toolbox'
cask 'razer-synapse'
cask 'spotify'
cask 'spotify-notifications'
cask 'dash'
cask 'virtualbox'
cask 'tunnelblick'
cask 'lastpass'
cask 'teamviewer'
cask 'docker'
cask 'the-unarchiver'
cask 'vagrant'
cask 'keybase'
cask 'numi'
cask 'keepingyouawake'
cask 'visual-studio-code'

## Fonts

cask 'font-menlo-for-powerline'
cask 'font-monoid-nerd-font'
